# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Realm-Playground' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StitchAPI
    # For core functionality and the Remote MongoDB Service
    pod 'StitchSDK', '= 6.4.0'
    # optional: for using the AWS service
    pod 'StitchSDK/StitchAWSService', '= 6.4.0'
    # optional: for using the Firebase Cloud Messaging service
    pod 'StitchSDK/StitchFCMService', '= 6.4.0'
    # optional: for using the HTTP service
    pod 'StitchSDK/StitchHTTPService', '= 6.4.0'
    # optional: for using the twilio service
    pod 'StitchSDK/StitchTwilioService', '= 6.4.0'
end
